package/rtl8723bs: drop package
Drop package as it doesn't build with latest kernel and project is not
maintained anymore: code has been removed in 2017 as driver is available
in the linux-next tree (cf.
https://github.com/hadess/rtl8723bs/commit/3bb1d33ad98c1d77b5e17a1b707e137b35e6d0a5):

In file included from /home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/drv_types.h:25,
                 from /home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./core/rtw_cmd.c:17:
/home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/autoconf.h:27:2: error: #error CONFIG_WIRELESS_EXT needs to be enabled for this driver to work
   27 | #error CONFIG_WIRELESS_EXT needs to be enabled for this driver to work
      |  ^~~~~
In file included from /home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/osdep_service.h:23,
                 from /home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/drv_types.h:27,
                 from /home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./core/rtw_cmd.c:17:
/home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/osdep_service_linux.h: In function ‘_init_timer’:
/home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/osdep_service_linux.h:97:8: error: ‘_timer’ {aka ‘struct timer_list’} has no member named ‘data’
   97 |  ptimer->data = (unsigned long)cntx;
      |        ^~
/home/autobuild/autobuild/instance-3/output-1/build/rtl8723bs-11ab92d8ccd71c80f0102828366b14ef6b676fb2/./include/osdep_service_linux.h:98:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
   98 |  init_timer(ptimer);
      |  ^~~~~~~~~~
      |  _init_timer

Fixes:
 - http://autobuild.buildroot.org/results/7a473e83d4a3d1e2228f4ee1282e85697de4ae5d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>